// Single sourcing point for the application's icon set (docs/ui-guidelines.md
// § Icons — "one icon set for the entire application"). Components and
// features import icons from here, never `lucide-react` directly, so a future
// icon-set change is a one-file edit.
export {
  AlertCircle as InfoIcon,
  AlertTriangle as WarningIcon,
  BarChart3 as ReportsIcon,
  Bell as NotificationsIcon,
  Boxes as InventoryIcon,
  CheckCircle2 as SuccessIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  Download as ExportIcon,
  History as ActivityIcon,
  Inbox as EmptyIcon,
  LayoutDashboard as DashboardIcon,
  Loader2 as SpinnerIcon,
  LogOut as LogOutIcon,
  Menu as MenuIcon,
  Minus as TrendFlatIcon,
  Monitor as SystemThemeIcon,
  Moon as DarkThemeIcon,
  Package as ProductsIcon,
  Receipt as BillingReportsIcon,
  Search as SearchIcon,
  ShoppingCart as OrdersIcon,
  Sun as LightThemeIcon,
  TrendingDown as TrendDownIcon,
  TrendingUp as TrendUpIcon,
  Trophy as ProductPerformanceIcon,
  User as UserIcon,
  Users as CustomersIcon,
  Wallet as RevenueIcon,
  X as CloseIcon,
  XCircle as DangerIcon,
} from 'lucide-react'
