query GetProductById($id: ID!) {
  productById(id: $id) {
    id
    title
    description
    brand
    sku
    status
    category {
      id
      name
      slug
    }
    variants {
      id
      sku
      price
      status
      isDefault
      attributes {
        key
        value
      }
      inventory {
        quantityOnHand
        quantityReserved
        sellableQuantity
        reorderThreshold
        updatedAt
      }
      createdAt
    }
    createdAt
    publishedAt
  }
}
